---
# defaults file for office

apt_deb_packages:
  - firefox
  - firefox-l10n-fr
  - remmina
  - vim

apt_deb_url:
  #- https://github.com/flameshot-org/flameshot/releases/download/v12.1.0/flameshot-12.1.0-1.debian-11.amd64.deb
  - https://github.com/obsidianmd/obsidian-releases/releases/download/v1.1.16/obsidian_1.1.16_amd64.deb

apt_deb_remove:
   #- anonsurf*
   #- blueman
   - brasero*
   - geany*
   - gimp*
   - libreoffice*
   - neovim
   - python3-neovim
   - qbittorrent*
   - tor
   - torbrowser-launcher
   - xboard
