---

# installing empire require an intance of mysql. So it is useless to just clone repository

# these scripts install, and manage the mysql instance

- name: "[Exegol:Empire] Copy Empire setup/start/stop scripts"
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/exegol/my-resources/bin/{{ item }}"
    mode: '0755'
  loop:
    - empire_setup
    - empire_start
    - empire_stop
    - starkiller_setup
    - starkiller_start
